### ISSUE TITLE
UI enhancement - add effects to the cards at main site

### ISSUE THREAD

**Issue by Priyanshi662** [Priyanshi662/FunFusion#10]
Can add effects such as onHover , improve the overall appearance of Cards

**Comment by diyabhandari** [comment]
Hi, please assign me this issue for JWoC

**Comment by Sruti-sahini** [comment]
Hello @Priyanshi662 
Please assign me this issue under JWoC'24

**Comment by Hacxmr** [comment]
Hey @Priyanshi662 
I would like to work on the enhancement of UI. Can you assign me this task under JWOC'24

**Comment by gayathrik23** [comment]
Hey @Priyanshi662
 Can you assign me this task under JWOC'24. i want to work on this

**Comment by DarshSohaliya** [comment]
Hey @Priyanshi662 I would like to work on that issue under JWOC

**Comment by Sruti-sahini** [comment]
Hey @Priyanshi662 
I have raised PR.
Please review.

**Comment by Priyanshi662** [comment]
closed as completed #23
