### ISSUE TITLE
Add a new feature or application 

### ISSUE THREAD

**Issue by Priyanshi662** [Priyanshi662/FunFusion#11]
Add new features/ application to the project : 
Steps - 
1.  make a folder for relevant js,CSS and HTML file
2.  make changes to the index.html file : 
3. Make a div with class="card" inside the body inside the div block :
     a. Add the image of the page added
     b. Add the name of the application in a h2 tag
     c. Add button for navigation

**Comment by aniket-1206** [comment]
I want to work on this issue , please assign this to me

**Comment by Sneha6003** [comment]
I would like to work on that issue under JWOC.

**Comment by Ananyamishra08** [comment]
Hello, @Priyanshi662  I would like to work on this , please assign it to me.

**Comment by ShreyaTiwari05** [comment]
Hii I am willing to pursue this issue under JWoC'24

**Comment by Priyanshi662** [comment]
@aniket-1206  updates? its been 4 days

**Comment by aniket-1206** [comment]
Hi @Priyanshi662 , i am still working on it , today is forth day , by EOD i will send a PR

**Comment by Priyanshi662** [comment]
@aniket-1206  okay!

**Comment by Parth4git** [comment]
@Priyanshi662 I want work on this issue to make a new Application  under JWOC. kindly assign this issue to me

**Comment by Sneha6003** [comment]
@Priyanshi662 please assign this issue to me under JWOC as i already requested for this issue last week. Thank You.
