### ISSUE TITLE
Add MIT License and code of conduct markdown files

### ISSUE THREAD

**Issue by manyaa1** [Priyanshi662/FunFusion#114]
Kindly assign me this under JWOC'24

**Comment by Priyanshi662** [comment]
@manyaa1  you can only be assigned one issue at a time.

**Comment by Anirban-Majumder** [comment]
Kindly assign me this under JWOC'24

**Comment by manyaa1** [comment]
@Priyanshi662 assign me this issue as I'm now done with previous issue
