### ISSUE TITLE
[Feature]Add Contributor Section

### ISSUE THREAD

**Issue by rishicds** [Priyanshi662/FunFusion#116]
Hi, I'd like to create a new page where the  contributors of this project will be shown and updated automatically,please assign this to me under JWOC'24

**Comment by Priyanshi662** [comment]
@rishicds you can only be assigned one issue at a time.

**Comment by Hacxmr** [comment]
Hey! @Priyanshi662 I'd like to contribute to this. Kindly assign me this under JWOC'24

**Comment by rishicds** [comment]
I have given a PR for my previous issue, if possible please assign this to me after that one is merged @Priyanshi662
