### ISSUE TITLE
Add color blast game!

### ISSUE THREAD

**Issue by shahil-afroz** [Priyanshi662/FunFusion#120]
![image](https://github.com/Priyanshi662/FunFusion/assets/137023904/2356a4ee-e351-49f9-a872-bbcbfb669deb)
![image](https://github.com/Priyanshi662/FunFusion/assets/137023904/7bcea229-f583-41a2-bce7-57c867aec22d)
![image](https://github.com/Priyanshi662/FunFusion/assets/137023904/f85a9c34-a52b-48a8-bd76-8fb2320ab131)

Its an fun game which consists of colorful rains we have to defend ourself with the help of arrow buttons

**Comment by vermaanurag1532** [comment]
please Assign it to me

**Comment by shahil-afroz** [comment]
please merge my PR....
