### ISSUE TITLE
addition of hit the bull's eye game 

### ISSUE THREAD

**Issue by GhoshAditi** [Priyanshi662/FunFusion#121]
@Priyanshi662  i would like to add the hit the bull's eye game. plz assign this to me under jwoc'24.
![U1n1titled](https://github.com/Priyanshi662/FunFusion/assets/144611267/027c3acc-074a-43ce-a8c6-9c8e9e909ede)

**Comment by GhoshAditi** [comment]
@Priyanshi662 plz assign it to me under jwoc'24. i would like to work on it.

**Comment by shahil-afroz** [comment]
this game is already present in the web page...
