### ISSUE TITLE
UI improvement of TicTacToe page.

### ISSUE THREAD

**Issue by Sruti-sahini** [Priyanshi662/FunFusion#13]
I have already worked upon this type of project.
I have good ideas about the UI of TicTacToe page
Please assign me this issue under JWoC'24

**Comment by Sruti-sahini** [comment]
Hi @Priyanshi662 Can I be assigned this issue ?

**Comment by Priyanshi662** [comment]
similar issue #12 opened

**Comment by vermaanurag1532** [comment]
i can make a super interactive Ui for you

**Comment by Sruti-sahini** [comment]
@Priyanshi662 Can I proceed with this issue ?

**Comment by Priyanshi662** [comment]
@Sruti-sahini yes sure, go ahead

**Comment by Sruti-sahini** [comment]
@Priyanshi662 I have raised PR for this issue. Please review it.

**Comment by Priyanshi662** [comment]
closing as completed #55
