### ISSUE TITLE
UI improvement of CitySearch

### ISSUE THREAD

**Issue by Shivani622** [Priyanshi662/FunFusion#14]
I have some creative ideas about this page.
Please assign me this issue under JWoC'24

**Comment by Priyanshi662** [comment]
please elaborate the ideas

**Comment by vermaanurag1532** [comment]
i can do this very easily you can assign it to me

**Comment by Priyanshi662** [comment]
@Shivani622  working on the issue?

**Comment by Priyanshi662** [comment]
@vermaanurag1532 assigned.

**Comment by vermaanurag1532** [comment]
ok

**Comment by Priyanshi662** [comment]
@vermaanurag1532 working on this issue?

**Comment by vermaanurag1532** [comment]
yeah

**Comment by vermaanurag1532** [comment]
please accept my PR
