### ISSUE TITLE
tic-tac-toe button and score

### ISSUE THREAD

**Issue by madhurima316** [Priyanshi662/FunFusion#15]
I want to add new match button to the tic-tac-toe game and would like to add the feature so it keeps track of the total number of wins , losses and ties .
Please assign me this issue under JWOC 2024.

**Comment by Priyanshi662** [comment]
@madhurima316  progress?

**Comment by madhurima316** [comment]
hopefully I would complete it by tomorrow.

**Comment by madhurima316** [comment]
Do I need to add colours and edit fonts for the button and the score section?

**Comment by madhurima316** [comment]
Then I may need another day.

**Comment by Priyanshi662** [comment]
@madhurima316 make a pr tomorrow with all thee changes.

**Comment by madhurima316** [comment]
can you please guide , how to set the restart functionality.
