### ISSUE TITLE
FEAT add uno game

### ISSUE THREAD

**Issue by AftabMankapure** [Priyanshi662/FunFusion#152]
FEAT add uno game

**Comment by Priyanshi662** [comment]
please complete the previous issue first!

**Comment by AftabMankapure** [comment]
Ok 
Don't assign to any one i will work on it after that issue

**Comment by Divyanshgarg-04** [comment]
@Priyanshi662 I would love to work on this issue. Can you please assign this issue to me under JWOC

**Comment by AftabMankapure** [comment]
@Divyanshgarg-04  i already start work on it 
so pls check any other issue
