### ISSUE TITLE
position footer to it appropriate position

### ISSUE THREAD

**Issue by Zenitssuu** [Priyanshi662/FunFusion#158]
few cards are below the footer, alignment it wrong, i want to work in it under JWOC'24. please assign it to me
![Screenshot (222)](https://github.com/Priyanshi662/FunFusion/assets/154405878/d3abb053-7f4a-447a-99aa-d3a5cff21ad4)

Assign it to me under JWOC'24

**Comment by Priyanshi662** [comment]
#143  duplicate
