### ISSUE TITLE
i want to create a chrome offline game

### ISSUE THREAD

**Issue by rimidutta** [Priyanshi662/FunFusion#161]
Chrome offline game (dinosaur jumping obstacle game) usinh html,css and javascript
please assign me under JWoC 

*************PREVIOUS ISSUES WERE CLOSED PLEASE ASSIGN ME A NEW ONE***************************************

**Comment by antilneeraj** [comment]
@rimidutta this game has already been made by another Mentee

URL: https://fun-fusion.netlify.app/assets/games/dinogame/
