### ISSUE TITLE
Feature: Rock, Paper & Scissors Game Addition

### ISSUE THREAD

**Issue by antilneeraj** [Priyanshi662/FunFusion#165]
I'd like to propose adding a Rock, Paper & Scissors game to the project, bringing a classic and fun element to enhance the user experience.

@Priyanshi662 Can you please assign this issue to me under JWOC?

**Comment by Priyanshi662** [comment]
already exists ! https://fun-fusion.netlify.app/assets/games/stone-paper-scissor%20game/
