### ISSUE TITLE
Fix various issues

### ISSUE THREAD

**Issue by itsmeabhishek03** [Priyanshi662/FunFusion#168]
Hey @Priyanshi662
1) Some Games are Rendering below footer as you can see in below Screenshot - 
![image](https://github.com/Priyanshi662/FunFusion/assets/104294494/d908c798-d229-43e5-ae12-f3d7b1193256)

2) Also, Search Icon Image is not rendering (due to incorrect path)
![image](https://github.com/Priyanshi662/FunFusion/assets/104294494/1bb18fc0-7d13-44cd-b00b-6ba4739b42f5)

3) I can make search bar more attractive using css

Please assign this issue to me under JWOC. Thank you

**Comment by Divyanshgarg-04** [comment]
@Priyanshi662 I would love to work on this issue under JWOC. Please assign this issue to me
