### ISSUE TITLE
Feature Request - Add "Go to Top" Button 

### ISSUE THREAD

**Issue by rahat2134** [Priyanshi662/FunFusion#175]
The current website lacks a "Go to Top" button, which can enhance user experience by allowing them to quickly navigate back to the top of the page. This feature is especially useful for pages with lengthy content, ensuring users can easily return to the start without manual scrolling.

Proposed Changes
Implement a "Go to Top" button that appears as users scroll down the page.
Position the button in a corner of the screen, maintaining visibility but not obstructing content.
Ensure smooth scrolling animation when users click the button.

Benefits
Improved user navigation by providing a convenient way to return to the top.
Enhances overall user experience, particularly on pages with extensive content.
Demonstrates a commitment to user-friendly design practices.

![image](https://github.com/Priyanshi662/FunFusion/assets/136263179/23ee2f4f-489c-4919-ad45-50a91b740618)
**image is just an example.

**Comment by rahat2134** [comment]
@Priyanshi662 assign me this under JWOC.

**Comment by rahat2134** [comment]
This button will be dynamic . *Advanced*

**Comment by thesri** [comment]
@Priyanshi662 please assign this to me under jwoc 2024 , if the assigned mentee couldnt do it in assignted time

**Comment by rahat2134** [comment]
@Priyanshi662 can you update difficulty level to hard? The button requires much logic and also it will also show how much you can scroll more in this website.

**Comment by Priyanshi662** [comment]
@thesri can you work on the issue?

**Comment by thesri** [comment]
> @thesri can you work on the issue?

Yes I'm willing to work on this under jwoc 2024
