### ISSUE TITLE
Please Allow me  to add COIN TOSS GAME

### ISSUE THREAD

**Issue by sudhanshu-77** [Priyanshi662/FunFusion#182]
Hi👋, @Priyanshi662 Please allow me to add COIN TOSS GAME  ,assign it to me under jwoc'24.

issue : #181

**Comment by sudhanshu-77** [comment]
@Priyanshi662 Please review my PR and merge. Thankyou

**Comment by Priyanshi662** [comment]
@sudhanshu-77 please make a PR only after assignment.

**Comment by sudhanshu-77** [comment]
> @sudhanshu-77 please make a PR only after assignment.

@Priyanshi662 ok I'll take care next time. 
Please add my point in Leaderboard. Thankyou
