### ISSUE TITLE
Add a Dark mode & Light mode

### ISSUE THREAD

**Issue by Surajit0573** [Priyanshi662/FunFusion#196]
I want to create a dark UI for this website and add a toggle button at the navbar to toggle between light mode and dark mode.

Please assign me under JWOC 2024, if approved.

**Comment by Surajit0573** [comment]
Hi @Priyanshi662 , Currently there are few major problem in UI of this project like...
1. There is no fixed navbar....

![image](https://github.com/Priyanshi662/FunFusion/assets/111490250/6bad3a93-3cd1-4a10-8ac0-86c6980dd77e)


Should I wait till navbar updated then I can add there a toggle button properly...or should I add anywhere.....

What should I do ??!!

**Comment by Priyanshi662** [comment]
@Surajit0573   #227   needs to be completed first, then you can work on the issue.

**Comment by Priyanshi662** [comment]
@Surajit0573 please start working on this issue
