### ISSUE TITLE
Code is breaking

### ISSUE THREAD

**Issue by manyaa1** [Priyanshi662/FunFusion#199]
There has been some issue as it appears in the images 
<img width="955" alt="image" src="https://github.com/Priyanshi662/FunFusion/assets/134845162/512932fa-89c8-414f-b336-3494faff1ab6">
<img width="929" alt="image" src="https://github.com/Priyanshi662/FunFusion/assets/134845162/3937c64c-9bf6-4364-8e2a-6553d4cab71e">
<img width="939" alt="image" src="https://github.com/Priyanshi662/FunFusion/assets/134845162/cef4fb4c-c813-4a09-94a1-2db39144b2c5">
Footer is not placed at the right place and the cards are repeating.

Kindly assign me this issue under JWOC'24

**Comment by AftabMankapure** [comment]
assign me under JWOC
