### ISSUE TITLE
[ADD] Want to add a Stone-Paper-Scissor game

### ISSUE THREAD

**Issue by ratnojitsaha** [Priyanshi662/FunFusion#21]
Stone-Paper-Scissor game card and it leads to a simple user vs computer stone paper scissor with logics of win lose and draw,
using html css and mostly js.

it will be having 3 icons representing different hand gesture for rock paper and scissors for user/player to click and play it,
and computer will randomly generate any such of three. On the two responses the score would be decided

please assign me this task under JWOC24

**Comment by Priyanshi662** [comment]
okay! assigned, please complete it in 2-3 days

**Comment by ratnojitsaha** [comment]
sure
