### ISSUE TITLE
Add hover effects to the buttons and align the game cards properly

### ISSUE THREAD

**Issue by Aswinr24** [Priyanshi662/FunFusion#22]
Would like to add hover effects to the game buttons and align the game cards properly in the webpage, since the margin towards the right is more and they are not centred
Please assign this to me under JWOC 24 @Priyanshi662

**Comment by KhushiAgarwal22** [comment]
would like to add the hover effect
Please assign this to me under JWOC 24.
@Priyanshi662

**Comment by KhushiAgarwal22** [comment]
I have made these similar changes under issue #57 already. Is there any other change required ?
@Priyanshi662
