### ISSUE TITLE
align all card of game in proper style 

### ISSUE THREAD

**Issue by AftabMankapure** [Priyanshi662/FunFusion#229]
align all card of game in proper style  
Current card alignment is 

https://github.com/Priyanshi662/FunFusion/assets/125949765/40f555d8-a6f7-4f09-9c1e-676b82afaba0

removing all empty space in card 
remove games which are below the footer

**Comment by AftabMankapure** [comment]
check the PR

**Comment by Priyanshi662** [comment]
@AftabMankapure please remove conflicts in PR.
