### ISSUE TITLE
FEAT add Ping pong game

### ISSUE THREAD

**Issue by AftabMankapure** [Priyanshi662/FunFusion#232]
FEAT add Ping pong game
assign me under jwoc

**Comment by Priyanshi662** [comment]
@AftabMankapure you can work on only one issue at a time

**Comment by AftabMankapure** [comment]
i will work on this after completing previous issue 
i make PR today for previous issue

**Comment by AftabMankapure** [comment]
assign me under JWOC after 
completion of previous issue

**Comment by AftabMankapure** [comment]
all previous issue is done 
already make pr for that

**Comment by vishal2005025** [comment]
I would like to work on this issue.
Please assign it to me under JWOC'2024.

**Comment by Parth4git** [comment]
@Priyanshi662 I want to work on this issue. Kindly assign this issue to me

**Comment by prakharsingh-74** [comment]
@Priyanshi662  i woukd like to work on this issue under jwoc 24

**Comment by Priyanshi662** [comment]
@vishal2005025 please start working on this issue

**Comment by vishal2005025** [comment]
Ok
