### ISSUE TITLE
Add Score

### ISSUE THREAD

**Issue by itsmeabhishek03** [Priyanshi662/FunFusion#234]
Hey @Priyanshi662 I would like to Add score and high score in Archery Game which will enhance user experience.

![image](https://github.com/Priyanshi662/FunFusion/assets/104294494/d76dffa9-03de-4a29-ac32-07327d551560)

Please assign it to me under JWOC

**Comment by Priyanshi662** [comment]
@itsmeabhishek03 progress?

**Comment by itsmeabhishek03** [comment]
hey @Priyanshi662 will raise PR soon will that be okay ?

**Comment by Priyanshi662** [comment]
@itsmeabhishek03 I'll be closing this issue, since it has been too much time
