### ISSUE TITLE
[FEAT] Adopt New File Structure

### ISSUE THREAD

**Issue by AftabMankapure** [Priyanshi662/FunFusion#24]
### Issue Title:
Proposal: Adopt New File Structure

### Description:
I propose the adoption of a new file structure for the FunFusion project. The current structure lacks clear organization, and I believe the proposed structure below will enhance the project's maintainability and scalability.

### Proposed File Structure:
```plaintext
FunFusion
|-- Asset
|   |-- images
|   |-- games
|   |   |-- Canvas
|   |   |   |-- index.html
|   |   |   |-- style.css
|   |   |   |-- script.js
|   |   |-- Text to speech
|   |       |-- index.html
|   |       |-- style.css
|   |       |-- script.js
|   |-- css
|   |   |-- style.css
|   |-- script
|   |   |-- script.js
|-- index.html
|-- README.md
```
###Current file structure
```plaintext
FunFusion
|-- Canvas
|   |-- index.html
|   |-- style.css
|   |-- script.js
|-- Text-to-Speech
|   |-- index.html
|   |-- style.css
|   |-- script.js
|-- index.html
|-- style.css
|-- README.md
```

### Advantages:
- Improved organization for assets.
- Better scalability for future growth.
- Easier maintenance with localized changes.

### Additional Information:
The proposed structure separates assets into logical subdirectories, making it more intuitive for developers to navigate the project.

Feel free to customize this template based on the specific details and conventions of your project.

**Comment by AftabMankapure** [comment]
### **Before assigning any issue to any one please think on my issue** 
 Now number of game in project is limited but some time count in increases that time it is hard to manage file structure 
@Priyanshi662

**Comment by AftabMankapure** [comment]
![image](https://github.com/Priyanshi662/FunFusion/assets/125949765/5c2d34e8-afad-44fd-8407-56ed6037fdd1)

it not come in easy label at least assign medium

**Comment by Priyanshi662** [comment]
@AftabMankapure yes sure, i'll assign medium
