### ISSUE TITLE
[Enhancement] Improve UI for contributor button

### ISSUE THREAD

**Issue by Priyanshi662** [Priyanshi662/FunFusion#241]
The button can be designed and improved in UI and aligned in the Navbar
[to be completed after issue #213 ]

**Comment by vishal2005025** [comment]
I would like to work on this issue.
Please assign it to me under JWOC'2024.

**Comment by prakharsingh-74** [comment]
@Priyanshi662 i would like to work on this issue under JWOC'24

**Comment by prakharsingh-74** [comment]
> The button can be designed and improved in UI and aligned in the Navbar [to be completed after issue #213 ]

@Priyanshi662 please assign me this issue

**Comment by prakharsingh-74** [comment]
Please assign me this issue @Priyanshi662 i have completed by previous issue.

**Comment by prakharsingh-74** [comment]
@Priyanshi662 please assign this issue to me
