### ISSUE TITLE
a feedback page

### ISSUE THREAD

**Issue by thesri** [Priyanshi662/FunFusion#251]
a feedback page which mainly gets the details about which game they liked most , which game has bugs if any some questions like this
i think this would enhace the website please assign me this issue under jwoc 2024

**Comment by Priyanshi662** [comment]
@thesri please complete the previous issue assigned first

**Comment by PranavBarthwal** [comment]
@Priyanshi662 I am willing to work on this under JWOC'24.
Please assign this to me.

**Comment by thesri** [comment]
> @thesri please complete the previous issue assigned first

I have started working on this @Priyanshi662 🥲please consider and I'll submit the pr for other issue before tonight only

**Comment by prakharsingh-74** [comment]
@Priyanshi662 please assign this issue to me
