### ISSUE TITLE
 ENHANCEMENT

### ISSUE THREAD

**Issue by ratnojitsaha** [Priyanshi662/FunFusion#254]
ADD A STICK HERO USER-FRIENDLY AND RESPONSIVE GAME **(USING HTML CSS AND PURE JAVASCRIPT)**.

WHICH WILL HAVE THE CONCEPTS OF --
1. WAITING
2. STRETCHING 
3. TURNING
4. WALKING
5. TRANSITIONS
6. FALLING

- ON TALKING ABOUT THE BASICS, THE GAME IS HAVING MULTIPLE PLATFORMS/WALLS TO WALK THROUGH.
- THE USER HAS TO WAIT AND DRAW A STICK , BY HOLDING THE MOUSE AND RELEASE TO DROP IT ON THE PLATFORM.
- AFTER THE SUCCESSFUL CONNECTION OF TWO PLATFORMS USER CAN WALK ON TO THE NEXT PLATFORM.
- THIS WILL CREATE A TRANSITION OF THE BACKGROUND AND UPCOMING PLATFORMS
- BUT, IF THE USER FAILS TO CONNECT THE WALLS , THEN THEY WILL FALL DOWN.

![Screenshot (476)](https://github.com/Priyanshi662/FunFusion/assets/110903082/0e9f3900-0d2f-43e1-9a65-6d08f037f04b)

PLEASE ASSIGN ME UNDER JWOC 2024

**Comment by Priyanshi662** [comment]
@ratnojitsaha are you still working on this issue?

**Comment by ratnojitsaha** [comment]
yes, its ready, will submit it tommorrow,
