### ISSUE TITLE
Bug: Mycanvas brush pointer not working properly

### ISSUE THREAD

**Issue by gitgoap** [Priyanshi662/FunFusion#259]
# Description

Whenever the brush in mycanvas is taken about the screen and brought back, it stops working.
Refer video.

https://github.com/Priyanshi662/FunFusion/assets/117789470/a71018c3-e3e7-4ad6-add5-714ffb8c267f

# Steps to reproduce the error

1. Go to https://fun-fusion.netlify.app/assets/games/canvas/mycanvas
2. Select brush icon
3. Drag the brush above the screen and bring it back.

**Comment by Priyanshi662** [comment]
@gitgoap did it get resolved?

**Comment by gitgoap** [comment]
I am not getting time to solve this issue, please assign it to someone else.

**Comment by Sneha6003** [comment]
I would like to work on this issue and also add some new features to the canvas like shapes.
I would like to work on this issue under jwoc.

**Comment by Priyanshi662** [comment]
@Sneha6003 please start working on it
