### ISSUE TITLE
build a dedicacted contact us page for your website

### ISSUE THREAD

**Issue by PranavBarthwal** [Priyanshi662/FunFusion#260]
I will build a dedicated contact us page for the website, which is a must have for every project
please assign this to me under JWOC'24
Inspiration:
![image](https://github.com/Priyanshi662/FunFusion/assets/110532770/5ff2be75-151c-4bd0-8324-06d809287300)

**Comment by prakharsingh-74** [comment]
@Priyanshi662 I  would like to work on this issue
