### ISSUE TITLE
Adding Hover effect to buttons in Riddles Game

### ISSUE THREAD

**Issue by Purwanshi08** [Priyanshi662/FunFusion#280]
Want to add hover effect for the Riddle Button and the Reveal riddle answer button in the Riddles game. Please assign me this issue under JWOC '24.

**Comment by thesri** [comment]
> Want to add hover effect for the Riddle Button and the Reveal riddle answer button in the Riddles game. Please assign me this issue under JWOC '24.

please assign this to me if the assigned mentee didnt do in the given time under jwoc 2024

**Comment by Priyanshi662** [comment]
@thesri please start working on this issue

**Comment by Purwanshi08** [comment]
@Priyanshi662 I have completed this issue. Just PR is left. Please assign this to me
back.

**Comment by thesri** [comment]
what should i do @Priyanshi662

**Comment by Priyanshi662** [comment]
@thesri you can try another issues. This is now completed
