### ISSUE TITLE
Adding Score Feature to the Snake Game

### ISSUE THREAD

**Issue by Purwanshi08** [Priyanshi662/FunFusion#281]
Want to add a Score Feature in the Snake game. Please assign me this issue under JWOC '24.

**Comment by AftabMankapure** [comment]
Assign me

**Comment by prakharsingh-74** [comment]
@Purwanshi08 can you please assign this issue to me under JWOC. As the given number of days has been passed to for the @AftabMankapure

**Comment by prakharsingh-74** [comment]
@Priyanshi662 if he will not be able to do this issue then please assign it to me.

**Comment by Priyanshi662** [comment]
@prakharsingh-74 please start working on this issue

**Comment by Purwanshi08** [comment]
@Priyanshi662 I have completed this issue. Just PR is left. Please assign it back to me.

**Comment by Purwanshi08** [comment]
I have completed this issue. I'm only left with PR. please assign it back to me
