### ISSUE TITLE
Adding effect to Word Scramble Game

### ISSUE THREAD

**Issue by Purwanshi08** [Priyanshi662/FunFusion#282]
Want to add effects to the Word Scramble game.  Please assign me this issue under JWOC '24.

**Comment by Priyanshi662** [comment]
@Purwanshi08 you need to complete previous issue assigned first..

**Comment by thesri** [comment]
> @Purwanshi08 you need to complete previous issue assigned first..

i can work on this, if the assigned mentee couldnt do it in the given time. under jwoc 2024 please assign me
