### ISSUE TITLE
Modifying the rate us section

### ISSUE THREAD

**Issue by Shubhra-Narang** [Priyanshi662/FunFusion#293]
The rate us section must have line for example" how do you like **Fun Fusion**?" on the left hand side of the section and the rate us button on the right corner of the section.This will enhance the appearence of this section.

Image showng how it looks now

<img width="457" alt="Screenshot 2024-02-06 at 4 57 34 PM" src="https://github.com/Priyanshi662/FunFusion/assets/143348689/8ecb2bcc-cedc-44ae-9e1a-1af71c0e398a">

After the changes

<img width="1422" alt="Screenshot 2024-02-06 at 6 17 19 PM" src="https://github.com/Priyanshi662/FunFusion/assets/143348689/ebbbc212-3b0f-463c-9a1e-ffd5ba83c902">

**Comment by Shubhra-Narang** [comment]
Please assign the issue to me!

**Comment by Priyanshi662** [comment]
@Shubhra-Narang  the navbar is being changed, so this might not be needed..

**Comment by Shubhra-Narang** [comment]
okay @Priyanshi662
