### ISSUE TITLE
Drum Kit Page Not Found

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [Priyanshi662/FunFusion#3]
whenever i click on drum kit. the page is not found
![Screenshot from 2024-01-12 02-36-41](https://github.com/Priyanshi662/FunFusion/assets/44281971/0cd06909-c4b0-41ad-8d87-eaf9291584d6)

**Comment by singhcodes26** [comment]
assign me this under JWOC'24

**Comment by Ananyamishra08** [comment]
Hello, @Priyanshi662  I would like to work on this , please assign it to me.

**Comment by Priyanshi662** [comment]
Hey @singhcodes26  kindly complete this issue by today and make the PR

**Comment by singhcodes26** [comment]
> Hey @singhcodes26 kindly complete this issue by today and make the PR

okay

**Comment by NaveenChandraAdhikari** [comment]
@Priyanshi662  can I do this under jwoc by today

**Comment by singhcodes26** [comment]
@Priyanshi662 i have resolved the issue. please check if it's working fine

**Comment by Priyanshi662** [comment]
@singhcodes26  Still it is showing not found, please recheck and make PR again.

**Comment by Priyanshi662** [comment]
Working fine, thanks for contributing! Closing this issue now.
