### ISSUE TITLE
add new game Sudoku

### ISSUE THREAD

**Issue by AftabMankapure** [Priyanshi662/FunFusion#312]
add new game Sudoku

**Comment by Priyanshi662** [comment]
@AftabMankapure  progress??

**Comment by bera474** [comment]
@Priyanshi662 Please assign me this issue under JWOC 2024 as the deadline has already been over !!

**Comment by bera474** [comment]
@Priyanshi662 Please assign me this issue under JWOC 2024

**Comment by SohanRC** [comment]
@Priyanshi662 Please assign me this issue under JWOC 2024 !!.

**Comment by AftabMankapure** [comment]
Done

**Comment by AftabMankapure** [comment]
@SohanRC
