### ISSUE TITLE
Random color generator

### ISSUE THREAD

**Issue by SuvayuN** [Priyanshi662/FunFusion#314]
A random color generator which can generate any random color at single click with rgb value of the colour. I want to make this as a contribution under JWOC'24

**Comment by Priyanshi662** [comment]
@SuvayuN progress?

**Comment by SohanRC** [comment]
@Priyanshi662 Assign me this issue under JWOC 2024

**Comment by SuvayuN** [comment]
> @SuvayuN progress?

I will complete the issue within tomorrow

**Comment by SohanRC** [comment]
> @Priyanshi662 Assign me this issue under JWOC 2024

Please assign me under JWOC 2024.
