### ISSUE TITLE
Screen Overflow Issue 

### ISSUE THREAD

**Issue by Shinjan-saha** [Priyanshi662/FunFusion#317]
<img width="960" alt="image" src="https://github.com/Priyanshi662/FunFusion/assets/116014977/1d9a07df-479f-4845-b420-44161553f912">
 there is an Overflow issue here I believe that i can solve this 
 Can you please assign this issue to me 
 After that i will create a Pull Request

**Comment by Shinjan-saha** [comment]
@Priyanshi662  is this issue ok? if yes can you please assign this to me

**Comment by Priyanshi662** [comment]
@Shinjan-saha yes its valid, please resolve it

**Comment by Priyanshi662** [comment]
@Shinjan-saha progress?
