### ISSUE TITLE
Fix Footer and Reintroduce contact us section

### ISSUE THREAD

**Issue by PranavBarthwal** [Priyanshi662/FunFusion#318]
Fix Footer and Reintroduce contact us section, due to distorted footer contact us section not visible.
Once this issue is fixed only then I can start working on #304 
please assign this to me under JWoC'24

![image](https://github.com/Priyanshi662/FunFusion/assets/110532770/8f6f5b0a-49a6-494a-8c36-5854e7a9dd5c)

**Comment by thesri** [comment]
@Priyanshi662 please assign this issue to me if the assigned mentee didnt do it
under jwoc 24
