### ISSUE TITLE
Fixed Navbar & Footer

### ISSUE THREAD

**Issue by Surajit0573** [Priyanshi662/FunFusion#333]
I want to 
1. Improve Navbar style
2. fix animation in top box 
3. improve style of search bar.
4. improve footer.
5. remove unnecessary youtube links.

![image](https://github.com/Priyanshi662/FunFusion/assets/111490250/3c54f123-24c5-4265-97ca-371bf2b366ef)

![image](https://github.com/Priyanshi662/FunFusion/assets/111490250/3f8aa660-a227-44a3-a25c-6d7e8a96b666)

Assign me under JWOC 2024,if approve.

**Comment by Priyanshi662** [comment]
@Surajit0573 any prgress?

**Comment by Surajit0573** [comment]
@Priyanshi662 working on it, will PR before end of the day.
