### ISSUE TITLE
Add Suduku Game - 4 x4 

### ISSUE THREAD

**Issue by Surajit0573** [Priyanshi662/FunFusion#355]
![image](https://github.com/Priyanshi662/FunFusion/assets/111490250/f85fd1d3-f7ab-42b3-9203-7a4d8ada6418)

**Comment by Priyanshi662** [comment]
@Surajit0573 can you integrate it in existing sudoku game if possible? it would really enhance the user experience.

**Comment by Surajit0573** [comment]
> @Surajit0573 can you integrate it in existing sudoku game if possible? it would really enhance the user experience.

@Priyanshi662, Okey, Assign me
