### ISSUE TITLE
Enhance and add navbar 

### ISSUE THREAD

**Issue by Sneha6003** [Priyanshi662/FunFusion#356]
I would like to make a better navbar and add it to all the pages like login page, contributors page, feedback page,etc for a smoother user experience.
Please assign this issue to me under JWOC.

**Comment by Priyanshi662** [comment]
@Sneha6003 progress?

**Comment by Sneha6003** [comment]
@Priyanshi662 Sorry i was unable to complete the assigned task, I request you to assign it to someone else.
