### ISSUE TITLE
remove title form home page 

### ISSUE THREAD

**Issue by AftabMankapure** [Priyanshi662/FunFusion#362]
Title: Remove title from 
![title](https://github.com/Priyanshi662/FunFusion/assets/125949765/605b8c00-49d2-447e-9607-1894f5740724)

**Comment by AftabMankapure** [comment]
Assign me under JWOC

**Comment by Priyanshi662** [comment]
![image](https://github.com/Priyanshi662/FunFusion/assets/77521822/6674df60-18e4-465d-ad5b-255ca15b67b3)
 
I think its displaying fine, and looking fine too.
