### ISSUE TITLE
BUG Remove index page body overflow 

### ISSUE THREAD

**Issue by AftabMankapure** [Priyanshi662/FunFusion#365]
### **BUG** Remove index page body overflow 

**Current** 

![overflow](https://github.com/Priyanshi662/FunFusion/assets/125949765/d503b25c-8779-4fad-ae89-e69985389744)

**New** 

![newover](https://github.com/Priyanshi662/FunFusion/assets/125949765/58dd8e51-f6d4-4ecb-9903-b96ce82f206d)

**Comment by AftabMankapure** [comment]
Assign me under JWOC

**Comment by Priyanshi662** [comment]
@AftabMankapure this bug has been resolved.
