### ISSUE TITLE
Navbar mismatch in FAQ page

### ISSUE THREAD

**Issue by AftabMankapure** [Priyanshi662/FunFusion#367]
### **Title:**  Add contact us menu in FAQ page navbar 

Home page navbar 

![h](https://github.com/Priyanshi662/FunFusion/assets/125949765/5e90c819-eb77-4182-8e17-8e4dee2d4e94)

FAQ page navbar

![hc](https://github.com/Priyanshi662/FunFusion/assets/125949765/7e51d50b-d227-4b4b-bbbc-2ee577766226)

**Comment by AftabMankapure** [comment]
Assign me under JWOC

**Comment by Priyanshi662** [comment]
@AftabMankapure  #356  is similar, if any bug occurs after the PR is made of that issue, you can work for it under this issue

**Comment by AftabMankapure** [comment]
I think i make PR for this now

**Comment by Priyanshi662** [comment]
@AftabMankapure yes sure
