### ISSUE TITLE
[ENHANCEMENT] ADD NEW GAME

### ISSUE THREAD

**Issue by ratnojitsaha** [Priyanshi662/FunFusion#368]
I WANT TO ADD A BASIC GAME MADE USING HTML CSS AND JAVASCRIPT, 
![Screenshot (540)](https://github.com/Priyanshi662/FunFusion/assets/110903082/0d2de7ad-296d-468f-9115-c5e6da46be67)

PLEASE ASSIGN ME UNDER JWOC 2024

**Comment by Priyanshi662** [comment]
@ratnojitsaha progress?

**Comment by ratnojitsaha** [comment]
@Priyanshi662 yes ongoing, will submit it by tommorrow,

**Comment by Priyanshi662** [comment]
@ratnojitsaha okay!
