### ISSUE TITLE
enhancement of rate us page

### ISSUE THREAD

**Issue by Hansawani** [Priyanshi662/FunFusion#372]
I want to enhance the rate us page as right now the UI is very basic.

**Comment by Priyanshi662** [comment]
@Hansawani progress?

**Comment by Hansawani** [comment]
Will complete it max by tomorrow....my exams were going on that's why I
couldn't complete it properly....will submit pr by tomorrow.

**Comment by Hansawani** [comment]
I have sent a pr for the issue. Please check and let me know if there are
any issues that need to be changed.
