### ISSUE TITLE
Add new Rock Paper Scissor game !

### ISSUE THREAD

**Issue by SohanRC** [Priyanshi662/FunFusion#381]
Add new Rock Paper Scissor game ! Here the user will pay with the Cpu ! Will make it completely Responsive !

**Comment by SohanRC** [comment]
@Priyanshi662 Please assign me under JWOC 2024.

**Comment by Priyanshi662** [comment]
@SohanRC please complete the previous issue assigned first!

**Comment by SohanRC** [comment]
@Priyanshi662 Ok , I will again raise this issue once i complete the previous one !

**Comment by SohanRC** [comment]
@Priyanshi662 Please assign me this issue now as i have completed the previous task !
