### ISSUE TITLE
[ADD] want to add suduko solver 

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [Priyanshi662/FunFusion#4]
I want to add suduko solver of 4*4 and 6*6 
please assign me this issue under JWOC'24 when coding phase starts

**Comment by Surajit0573** [comment]
Hi, @Sriparno08, It has been 5 days since this issue was assigned. and the time limit for a medium issue was 3 days...so please re-assign this to me under 2024...I want to work on this issue.
