### ISSUE TITLE
[FEA]: Add a fun food slicer game.

### ISSUE THREAD

**Issue by Ashutosh104** [Priyanshi662/FunFusion#42]
A fun food slicer game should be there.

**Comment by Priyanshi662** [comment]
you can only be assigned one issue at the a time, so please complete the previous one first!

**Comment by vishal2005025** [comment]
I have read the issue and I want to work on it .
please assign it to me under JWOC'2024.

**Comment by Priyanshi662** [comment]
@vishal2005025 please start working on it

**Comment by vishal2005025** [comment]
mam, I have completed this issue and created pull request .
please check.

**Comment by vishal2005025** [comment]
Mam, I have completed this issue and created new pull request after all the changes in the structure of the project as you told in  discord channel.
please check...

**Comment by Priyanshi662** [comment]
@vishal2005025 please mention your full name

**Comment by vishal2005025** [comment]
Name : Vishal Malyan
