### ISSUE TITLE
[UI enhancement]:UI enhancement in My Canvas 

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [Priyanshi662/FunFusion#5]
This enhancement request focuses on elevating the user interface of the my canvas webpage by replacing text labels with drum-related icons like pen with actual pen picture.The objective is to enhance the visual appeal and user experience for users interacting with the canvas.

please assign me this under JWOC'24

**Comment by Priyanshi662** [comment]
rather than replacing, I think it would look better having both text and icon side by side

**Comment by Hacxmr** [comment]
Hey! @Priyanshi662 I would want to contribute to this under JWOC'24

**Comment by NaveenChandraAdhikari** [comment]
> rather than replacing, I think it would look better having both text and icon side by side

@Priyanshi662 okk I'll do that assign me under jwoc

**Comment by Priyanshi662** [comment]
@NaveenChandraAdhikari  updates?

**Comment by NaveenChandraAdhikari** [comment]
> @NaveenChandraAdhikari updates?

I will generate a PR  by tomorrow cuz my exams are going on .But I'll make sure to do it ASAP

**Comment by NaveenChandraAdhikari** [comment]
![Screenshot from 2024-01-16 23-48-10](https://github.com/Priyanshi662/FunFusion/assets/44281971/958a4f43-0f73-4353-96fd-f656c8ba4208)
@Priyanshi662  is this right or should I change the position of icon

**Comment by Priyanshi662** [comment]
@NaveenChandraAdhikari  this looks fine , you can raise a PR
