### ISSUE TITLE
addition of snake game 

### ISSUE THREAD

**Issue by GhoshAditi** [Priyanshi662/FunFusion#51]
@Priyanshi662 i would like to add the snake game. plz assign it to me under jwoc'24

**Comment by vishal2005025** [comment]
Mam, I have read the issue and I would like to work on this issue.
Please assign it to me under JWOC'2024.

**Comment by Priyanshi662** [comment]
@vishal2005025 assigned.

**Comment by GhoshAditi** [comment]
@Priyanshi662 i have already given a pr of this issue and its merged as well many days ago. u can check. i dont know why u unassigned me :)

**Comment by GhoshAditi** [comment]
@Priyanshi662 this was my pr from 5 days ago which I already merged as well


![image](https://github.com/Priyanshi662/FunFusion/assets/144611267/654fa34d-7f37-43b6-b2b0-dba8bc6cf685)
