### ISSUE TITLE
Adding the Stone Paper Scissors Game

### ISSUE THREAD

**Issue by Lakshya0018UP** [Priyanshi662/FunFusion#56]

**Comment by Lakshya0018UP** [comment]
Assign it to me Under JWOC👍
@Priyanshi662

**Comment by KhushiAgarwal22** [comment]
I would like to contribute to this issue.Please assign it to me under jwoc.
@Priyanshi662

**Comment by Priyanshi662** [comment]
there is a similar issue opened #46
