### ISSUE TITLE
UI Enhancement: Center Pokemon Generation Content on Webpage

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [Priyanshi662/FunFusion#6]
The current state of the Pokemon generator webpage does not present an optimal user experience as the generated content is not centered on the page. This enhancement request focuses on improving the layout by centering the Pokemon generation content, ensuring a more visually appealing and user-friendly design.

Assign me this under JWOC'24

**Comment by Priyanshi662** [comment]
@NaveenChandraAdhikari  any updates?

**Comment by vishal2005025** [comment]
Name : vishal malyan
Git : https://github.com/vishal2005025
I have read the issue and go through the code and I have some idea ..
I eagerly want to work on it .
please assign it to me .

**Comment by NaveenChandraAdhikari** [comment]
@Priyanshi662  raising pr  in a hour or two
