### ISSUE TITLE
[Add] A Sudoku Game 

### ISSUE THREAD

**Issue by smilewithkhushi** [Priyanshi662/FunFusion#62]
Addition of very popular Sudoku game, consisting of 9x9 grid.
Each box, row, and column will contain the numbers 1 to 9 without repetition. 
Would love to work on this game and contribute to the project! Hoping you'd assign me this issue : )

**Comment by Priyanshi662** [comment]
@smilewithkhushi there is another issue opened same as this one. Please review the issues then raise.
