### ISSUE TITLE
Add a QR Code Generator

### ISSUE THREAD

**Issue by SohanRC** [Priyanshi662/FunFusion#66]
I am attaching the screenshot below.
![Screenshot 2024-01-20 132049](https://github.com/Priyanshi662/FunFusion/assets/124901633/760a92eb-6991-4694-b355-4f4bdf5f1f08)

**Comment by SohanRC** [comment]
Please assign me under JWOC 2024.

**Comment by vermaanurag1532** [comment]
please Assign it to me
