### ISSUE TITLE
ADD pokemon information and search option

### ISSUE THREAD

**Issue by Pranav-Rastogi1** [Priyanshi662/FunFusion#7]
here you can search for a pokemon by typing its name .
Assign me this under JWOC'24.

**Comment by Priyanshi662** [comment]
That would become a pokedexrather than  random generator, can you rather try for randomly generating pokemons based on its type?

**Comment by Jenis07** [comment]
Can you assign me this issue under JWOC?

**Comment by Priyanshi662** [comment]
@Jenis07 updates?

**Comment by Jenis07** [comment]
sorry for the delay ma'm but i have working on this from now.
