### ISSUE TITLE
Add Wordle Game 

### ISSUE THREAD

**Issue by itsmeabhishek03** [Priyanshi662/FunFusion#74]
Hey @Priyanshi662 I would Like to contribute the Wordle Game in your awesome repository. Please assign it to me under JWOC. thank you.

**Comment by Priyanshi662** [comment]
@itsmeabhishek03  assigned!

**Comment by itsmeabhishek03** [comment]
Hey @Priyanshi662 I have created Wordle game using React can i upload it or you Strictly need only a html, css, javascript project?

**Comment by vermaanurag1532** [comment]
please Assign it to me

**Comment by itsmeabhishek03** [comment]
> please Assign it to me

hey @vermaanurag1532 I am working on this issue and probably will raise PR today late night you can check some other issues thank you
