### ISSUE TITLE
Icon is not present

### ISSUE THREAD

**Issue by itsmeabhishek03** [Priyanshi662/FunFusion#75]
Hey @Priyanshi662 in your app the icon is not present i can add icon to it. please assign this issue to me under JWOC. Thank you.

**Comment by Priyanshi662** [comment]
@itsmeabhishek03  you can work on only one issue at a time.

**Comment by prakharsingh-74** [comment]
![Screenshot 2024-01-21 152614](https://github.com/Priyanshi662/FunFusion/assets/148339919/d3aa8584-82b5-4d39-8e48-6a989651045a)
@Priyanshi662 I would like to work on this issue under JWOC
here i have designed your app logo

**Comment by itsmeabhishek03** [comment]
> @itsmeabhishek03 you can work on only one issue at a time.

Okay so after finishing the other issue will I get this issue or anyone else will get it ?

**Comment by viendimine** [comment]
@Priyanshi662 pls assign me this issue under 'JWOC'

**Comment by itsmeabhishek03** [comment]
> @itsmeabhishek03 you can work on only one issue at a time.

hey @Priyanshi662 I have completed my previous issue now can i work on this issue ?
