### ISSUE TITLE
Riddles

### ISSUE THREAD

**Issue by prasukjain07** [Priyanshi662/FunFusion#81]
We can add a games of riddles

**Comment by Priyanshi662** [comment]
@prasukjain07 you can only work on one issue at a time.

**Comment by prasukjain07** [comment]
@Priyanshi662 I resolve the previous issue, please check that and assign this issue to me under JWOC

**Comment by prasukjain07** [comment]
@Priyanshi662 
I push the riddles page also, please check my PR

**Comment by vermaanurag1532** [comment]
please Assign it to me
