### ISSUE TITLE
Feature: Add Password Generator

### ISSUE THREAD

**Issue by Prithwi32** [Priyanshi662/FunFusion#88]
I would like to add password generator to ur repo...
Its ans example and could be changed some styling as per your feedback
![image](https://github.com/Priyanshi662/FunFusion/assets/115262737/1a87f7dc-3cda-4c7f-9149-cdabb7ed9376)

**Comment by Prithwi32** [comment]
> I would like to add password generator to ur repo... Its ans example and could be changed some styling as per your feedback ![image](https://private-user-images.githubusercontent.com/115262737/298387516-1a87f7dc-3cda-4c7f-9149-cdabb7ed9376.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NDU2NjQsIm5iZiI6MTcwNTg0NTM2NCwicGF0aCI6Ii8xMTUyNjI3MzcvMjk4Mzg3NTE2LTFhODdmN2RjLTNjZGEtNGM3Zi05MTQ5LWNkYWJiN2VkOTM3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMVQxMzU2MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMWQxOGFlZDg3YjU1YmJkYTQ5YzJiNWM0ODdjYmQ2ZTRkMzBiODg1Y2UxODNkNjA4ZmUxYWRiZWRiZmM2NDE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ufs1tmlqHZU0aIjYwoqSVXJI2fahxcg9QEm7xt2okT4)

I would like to work on this issue under JWOC

**Comment by Priyanshi662** [comment]
@Prithwi32  looks great , assigned!

**Comment by Prithwi32** [comment]
@Priyanshi662 I made PR kindly check it and let me know the feedback
