### ISSUE TITLE
Improve the README 

### ISSUE THREAD

**Issue by Priyanshi662** [Priyanshi662/FunFusion#9]
add some description about the project, fix grammatical mistakes.

**Comment by diyabhandari** [comment]
Please assign me this issue under JWoC '24.

**Comment by singhcodes26** [comment]
consider me for this under JWOC'24

**Comment by Sruti-sahini** [comment]
Hello @Priyanshi662 
Please assign me this issue under JWoC'24.

**Comment by Sruti-sahini** [comment]
Hello @Priyanshi662 
Please assign me this issue under JWoC'24

**Comment by Sneha6003** [comment]
I would like to work on that issue under JWOC.

**Comment by Priyanshi662** [comment]
closing as completed #18
